version: 2

sphinx:
   configuration: doc/conf.py

# build:
#   os: ubuntu-22.04
#   tools:
#     python: "3.9"

python:
  version: "3"
  install:
    - method: pip
      path: .
    - requirements: doc/requirements.txt
