version: 2

sphinx:
   configuration: doc/conf.py

conda:
    environment: doc/doc-requirements.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# python:
#   install:
#     - method: pip
#       path: .
