name: test-environment
channels:
  - conda-forge
dependencies:
  - python<3.14
  - compliance-checker
  - dask
  - git-lfs
  - gsw
  - joblib
  - matplotlib-base
  - netcdf4
  - numpy
  - pandas
  - pre-commit
  - pyarrow
  - pytest
  - pyyaml
  - scipy
  - sqlite
  - tqdm
  - xarray
  - xmltodict
