name: test-environment
channels:
  - conda-forge
dependencies:
  - python <= 3.12
  - compliance-checker
  - dask
  - git-lfs
  - joblib
  - matplotlib-base
  - netcdf4
  - numpy
  - pandas
  - pre-commit
  - pyarrow
  - pytest
  - pyyaml
  - scipy
  - seawater
  - sqlite
  - tqdm
  - xarray
  - xmltodict
