import pathlib

from setuptools import find_packages, setup

import versioneer

here = pathlib.Path(__file__).parent.resolve()

# Get the long description from the README file
long_description = (here / "README.md").read_text(encoding="utf-8")

# used https://github.com/pypa/sampleproject/blob/master/setup.py

setup(
    name="stglib",
    version=versioneer.get_version(),
    cmdclass=versioneer.get_cmdclass(),
    description=("Process data from a variety of oceanographic instrumentation"),
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="U.S. Geological Survey",
    author_email="dnowacki@usgs.gov",
    url="https://github.com/USGS-CMG/stglib",
    license="Public domain",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    # install_requires=['numpy', 'netCDF4', 'xarray'],
    python_requires=">=3.8",
    packages=find_packages(exclude=["doc", "tests"]),
    scripts=[
        # "scripts/runaqdhdr2cdf.py",
        # "scripts/runaqdcdf2nc.py",
        # "scripts/runaqdhrhdr2cdf.py",
        # "scripts/runaqdhrcdf2nc.py",
        # "scripts/runhwlbcsv2cdf.py",
        # "scripts/runhwlbcdf2nc.py",
        # "scripts/runiqmat2cdf.py",
        # "scripts/runiqcdf2nc.py",
        # "scripts/runrskrsk2cdf.py",
        # "scripts/runrskcsv2cdf.py",
        # "scripts/runrskcdf2nc.py",
        # "scripts/runrsknc2waves.py",
        # "scripts/runrsknc2diwasp.py",
        # "scripts/runecocsv2cdf.py",
        # "scripts/runecocdf2nc.py",
        # "scripts/runexocsv2cdf.py",
        # "scripts/runexocdf2nc.py",
        # "scripts/runtrollcsv2cdf.py",
        # "scripts/runtrollcdf2nc.py",
        # "scripts/runwvswad2cdf.py",
        # "scripts/runwvscdf2nc.py",
        # "scripts/runwvsnc2diwasp.py",
        # "scripts/runwvsnc2waves.py",
        "scripts/aqdturnaround.py",
        "scripts/exoturnaround.py",
        # "scripts/runwxtcsv2cdf.py",
        # "scripts/runwxtcdf2nc.py",
        # "scripts/runeofelog2cdf.py",
        # "scripts/runeofecdf2nc.py",
        # "scripts/runvecdat2cdf.py",
        # "scripts/runveccdf2nc.py",
        # "scripts/runsigmat2cdf.py",
        # "scripts/runsigraw2cdf.py",
        # "scripts/runsigcdf2nc.py",
    ],
    entry_points={
        "console_scripts": [
            "runaqdhdr2cdf.py=stglib.core.runcmd:runaqdhdr2cdf",
            "runaqdcdf2nc.py=stglib.core.runcmd:runaqdcdf2nc",
            "runaqdhrhdr2cdf.py=stglib.core.runcmd:runaqdhrhdr2cd",
            "runaqdhrcdf2nc.py=stglib.core.runcmd:runaqdhrcdf2nc",
            "runhwlbcsv2cdf.py=stglib.core.runcmd:runhwlbcsv2cdf",
            "runhwlbcdf2nc.py=stglib.core.runcmd:runhwlbcdf2nc",
            "runiqmat2cdf.py=stglib.core.runcmd:runiqmat2cdf",
            "runiqcdf2nc.py=stglib.core.runcmd:runiqcdf2nc",
            "runrskrsk2cdf.py=stglib.core.runcmd:runrskrsk2cdf",
            "runrskcsv2cdf.py=stglib.core.runcmd:runrskcsv2cdf",
            "runrskcdf2nc.py=stglib.core.runcmd:runrskcdf2nc",
            "runrsknc2waves.py=stglib.core.runcmd:runrsknc2waves",
            "runrsknc2diwasp.py=stglib.core.runcmd:runrsknc2diwas",
            "runecocsv2cdf.py=stglib.core.runcmd:runecocsv2cdf",
            "runecocdf2nc.py=stglib.core.runcmd:runecocdf2nc",
            "runexocsv2cdf.py=stglib.core.runcmd:runexocsv2cdf",
            "runexocdf2nc.py=stglib.core.runcmd:runexocdf2nc",
            "runtrollcsv2cdf.py=stglib.core.runcmd:runtrollcsv2cd",
            "runtrollcdf2nc.py=stglib.core.runcmd:runtrollcdf2nc",
            "runwvswad2cdf.py=stglib.core.runcmd:runwvswad2cdf",
            "runwvscdf2nc.py=stglib.core.runcmd:runwvscdf2nc",
            "runwvsnc2diwasp.py=stglib.core.runcmd:runwvsnc2diwas",
            "runwvsnc2waves.py=stglib.core.runcmd:runwvsnc2waves",
            "runwxtcsv2cdf.py=stglib.core.runcmd:runwxtcsv2cdf",
            "runwxtcdf2nc.py=stglib.core.runcmd:runwxtcdf2nc",
            "runeofelog2cdf.py=stglib.core.runcmd:runeofelog2cdf",
            "runeofecdf2nc.py=stglib.core.runcmd:runeofecdf2nc",
            "runvecdat2cdf.py=stglib.core.runcmd:runvecdat2cdf",
            "runveccdf2nc.py=stglib.core.runcmd:runveccdf2nc",
            "runsigmat2cdf.py=stglib.core.runcmd:runsigmat2cdf",
            "runsigraw2cdf.py=stglib.core.runcmd:runsigraw2cdf",
            "runsigcdf2nc.py=stglib.core.runcmd:runsigcdf2nc",
        ],
    },
    include_package_data=True,
)
