basefile: 'AQ107601'
filename: '10761Baqd'   # name of output file, -raw.cdf or .nc will be appended to this
LatLonDatum: 'NAD83'
ClockError: 0 # sec, negative is slow
orientation: 'UP'          # use this to identify orientation of profiler
head_rotation: 'horizontal'
initial_instrument_height: 0.15  # meters - estimated!!!
initial_instrument_height_note: ''
zeroed_pressure: 'Yes' # was pressure zeroed before deployment
cutoff_ampl: 0   # set to 0, otherwise it automatically specifies cutoff based on amplitude which is a weird thing to do
trim_method: 'Water Level SL'  # Water Level SL trims bin if any part of bin or side lobe is out of water - works best when pressure is corrected for atmospheric
P_1ac_note: 'Corrected for variations in atmospheric pressure using Grand Bay NERR met station (GNDCRMET).'
maximum_wp: 4
minimum_wh: 0.02
wp_ratio: 2