name: stglib-docs
channels:
  - conda-forge
dependencies:
  - python<3.14
  - compliance-checker
  - dask
  - git-lfs
  - gsw
  - joblib
  - matplotlib-base
  - netcdf4
  - numpy
  - pandas
  - pre-commit
  - pyarrow
  - pytest
  - pyyaml
  - scipy
  - sqlite
  - tqdm
  - xarray
  - xmltodict
  - sphinx==6.2.1
  - sphinx-argparse==0.4.0
  - sphinx_rtd_theme==3.0.1
  - numpydoc
