name: stglib-docs
channels:
  - conda-forge
dependencies:
  - python
  - compliance-checker
  - dask
  - dolfyn
  - matplotlib-base
  - netcdf4
  - numpy
  - pandas
  - pre-commit
  - pyarrow
  - pytest
  - pyyaml
  - scipy
  - seawater
  - tqdm
  - xarray
  - xmltodict
  - sphinx==5.1.1
  - sphinx-argparse==0.2.5
  - sphinx_rtd_theme==1.0.0
  - numpydoc
