name: stglib

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     lfs: true
      - uses: nschloe/action-cached-lfs-checkout@v1
      - run: git lfs checkout
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-environment
          environment-file: requirements.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - run: |
          conda info
          conda list
          pip install --no-deps -e .
          pytest
