name: stglib

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: git lfs checkout
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-environment
          environment-file: requirements-py38.yml
          python-version: 3.8
          auto-activate-base: false
      - run: |
          conda info
          conda list
          pip install --no-deps -e .
          pytest
